"""Step 4 — profile the dataset and (re)generate ``data/data_card.md``.

Counts images and per-class instances across the dataset so we can see class
balance (e.g. 600 jugs vs 15 pockets) before training. Writes the data card.

Run:  python data/scripts/stats.py            # profiles interim_dir by default
      python data/scripts/stats.py --root data/processed
"""
from __future__ import annotations

import argparse
import logging
from collections import Counter
from pathlib import Path
from typing import Any

from config import Paths, load_config, resolve_paths
from labels import iter_label_files, parse_boxes

logger = logging.getLogger(__name__)


def profile(root: Path, classes: list[str]) -> tuple[int, Counter]:
    """Return (image/label-file count, per-class-index instance counts)."""
    counts: Counter = Counter()
    n_files = 0
    for label_file in iter_label_files(root):
        n_files += 1
        for box in parse_boxes(label_file):
            counts[box.cls] += 1
    return n_files, counts


def render_data_card(root: Path, classes: list[str], n_files: int, counts: Counter,
                     cfg: dict[str, Any]) -> str:
    """Render the data card markdown from the profiling results."""
    total = sum(counts.values()) or 1
    rf = cfg["roboflow"]
    lines = [
        "# Data Card — Climbing Holds Dataset",
        "",
        "_Generated by `data/scripts/stats.py`. Re-run after any pipeline change._",
        "",
        "## Source",
        f"- Roboflow: `{rf['workspace']}/{rf['project']}` version **{rf['version']}** "
        f"(format `{rf['format']}`).",
        "- Custom photos: team phone captures of the wall/holds, annotated in Roboflow.",
        "",
        "## Conventions",
        f"- Image size: **{cfg['image_size']}** (locked).",
        f"- Classes (order matters): `{classes}`.",
        "",
        f"## Counts (profiled at `{root.name}/`)",
        f"- Label files: **{n_files}**",
        f"- Total boxes: **{sum(counts.values())}**",
        "",
        "| idx | class | instances | share |",
        "|----:|-------|----------:|------:|",
    ]
    for idx, name in enumerate(classes):
        n = counts.get(idx, 0)
        lines.append(f"| {idx} | {name} | {n} | {100 * n / total:.1f}% |")
    unknown = sorted(c for c in counts if c >= len(classes))
    if unknown:
        lines.append("")
        lines.append(f"> ⚠️ Found label indices outside the class list: {unknown}")
    lines.append("")
    lines.append("## How it was built")
    lines.append("download → clean → ingest_custom → split → export "
                 "(see `data/scripts/run_pipeline.py`).")
    lines.append("")
    return "\n".join(lines)


def run(cfg: dict[str, Any], paths: Paths, root: Path | None = None) -> Path:
    """Profile ``root`` (default interim) and write ``paths.data_card``."""
    root = root or paths.interim_dir
    classes = cfg["classes"]
    if not root.exists():
        logger.warning("Nothing to profile at %s yet.", root)
    n_files, counts = profile(root, classes)
    card = render_data_card(root, classes, n_files, counts, cfg)
    paths.data_card.parent.mkdir(parents=True, exist_ok=True)
    paths.data_card.write_text(card, encoding="utf-8")
    logger.info("Profiled %d label files; wrote data card to %s", n_files, paths.data_card)
    return paths.data_card


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", default=None, help="Path to config.yaml (default: repo root).")
    ap.add_argument("--root", default=None, help="Dataset dir to profile (default: interim_dir).")
    args = ap.parse_args(argv)

    cfg = load_config(args.config)
    paths = resolve_paths(cfg)
    root = (paths.root / args.root).resolve() if args.root else None
    run(cfg, paths, root)
    return 0


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    raise SystemExit(main())
